
resource_registry:
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/templates/custom-nics/compute-custom.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/custom-nics/controller-custom.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: /home/stack/templates/custom-nics/ceph-storage-custom.yaml

parameter_defaults:
  DnsServers: ["8.8.8.8"]
  InternalApiNetworkVlanID: 201
  StorageNetworkVlanID: 202
  StorageMgmtNetworkVlanID: 203
  TenantNetworkVlanID: 204
  ManagementNetworkVlanID: 205

  ControlPlaneSubnet: "ctlplane-subnet"
  ExternalNetCidr: "10.1.0.0/16"
  InternalApiNetCidr: "172.16.2.0/24"
  StorageNetCidr: '172.16.1.0/24'
  StorageMgmtNetCidr: '172.16.3.0/24'
  TenantNetCidr: '172.16.0.0/24'
  ManagementNetCidr: '10.0.1.0/24'
 
  ExternalInterfaceDefaultRoute: '10.1.0.254'
  ControlPlaneDefaultRoute: '192.168.194.1'

  ExternalAllocationPools: [{"start": "10.1.195.10", "end": "10.1.195.50"}]
  InternalApiAllocationPools: [{'start': '172.16.2.4', 'end': '172.16.2.250'}]
  StorageAllocationPools: [{'start': '172.16.1.4', 'end': '172.16.1.250'}]
  StorageMgmtAllocationPools: [{'start': '172.16.3.4', 'end': '172.16.3.250'}]
  TenantAllocationPools: [{'start': '172.16.0.4', 'end': '172.16.0.250'}]
  ManagementAllocationPools: [{'start': '10.0.1.4', 'end': '10.0.1.250'}]


